# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(800, 450)
        self.frame = QtWidgets.QFrame(Mainwindow)
        self.frame.setGeometry(QtCore.QRect(200, 20, 551, 400))
        self.frame.setMinimumSize(QtCore.QSize(551, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(Mainwindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 141, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.frame.setGeometry(QtCore.QRect(200, 20, 551, 400))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "图片处理工具"))
        self.pushButton_1.setText(_translate("Mainwindow", "灰度/二值化"))
        self.pushButton_2.setText(_translate("Mainwindow", "图像翻转"))
        self.pushButton_3.setText(_translate("Mainwindow", "图像锐化"))
        self.pushButton_4.setText(_translate("Mainwindow", "滤波"))
        self.pushButton_5.setText(_translate("Mainwindow", "检测"))
        self.pushButton_6.setText(_translate("Mainwindow", "特征检测"))


class Ui_Formwin1(object):
    def setupUi(self, Formwin1):
        Formwin1.setObjectName("Formwin1")
        Formwin1.resize(571, 400)
        self.label_tips = QtWidgets.QLabel(Formwin1)
        self.label_tips.setGeometry(QtCore.QRect(30, 280, 51, 41))
        self.label_tips.setObjectName("label_tips")
        self.label_daichuli = QtWidgets.QLabel(Formwin1)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.pushButton_save = QtWidgets.QPushButton(Formwin1)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_turntotwo = QtWidgets.QPushButton(Formwin1)
        self.pushButton_turntotwo.setGeometry(QtCore.QRect(340, 290, 101, 31))
        self.pushButton_turntotwo.setObjectName("pushButton_turntotwo")
        self.label_jieguo = QtWidgets.QLabel(Formwin1)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_turntoGray = QtWidgets.QPushButton(Formwin1)
        self.pushButton_turntoGray.setGeometry(QtCore.QRect(110, 290, 101, 31))
        self.pushButton_turntoGray.setObjectName("pushButton_turntoGray")
        self.pushButton_load = QtWidgets.QPushButton(Formwin1)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")

        self.retranslateUi(Formwin1)
        QtCore.QMetaObject.connectSlotsByName(Formwin1)

    def retranslateUi(self, Formwin1):
        _translate = QtCore.QCoreApplication.translate
        Formwin1.setWindowTitle(_translate("Formwin1", "Form"))
        self.label_tips.setText(_translate("Formwin1", "操作："))
        self.label_daichuli.setText(_translate("Formwin1", "待处理"))
        self.pushButton_save.setText(_translate("Formwin1", "保存图片"))
        self.pushButton_turntotwo.setText(_translate("Formwin1", "将图片二值化"))
        self.label_jieguo.setText(_translate("Formwin1", "结果"))
        self.pushButton_turntoGray.setText(_translate("Formwin1", "转为灰度图"))
        self.pushButton_load.setText(_translate("Formwin1", "选择图片"))

class Ui_Formwin2(object):
    def setupUi(self, Formwin2):
        Formwin2.setObjectName("Formwin2")
        Formwin2.resize(571, 400)
        self.pushButton_fun0 = QtWidgets.QPushButton(Formwin2)
        self.pushButton_fun0.setGeometry(QtCore.QRect(110, 290, 101, 31))
        self.pushButton_fun0.setObjectName("pushButton_fun0")
        self.pushButton_save = QtWidgets.QPushButton(Formwin2)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_tips = QtWidgets.QLabel(Formwin2)
        self.label_tips.setGeometry(QtCore.QRect(30, 280, 51, 41))
        self.label_tips.setObjectName("label_tips")
        self.label_daichuli = QtWidgets.QLabel(Formwin2)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.pushButton_fun1 = QtWidgets.QPushButton(Formwin2)
        self.pushButton_fun1.setGeometry(QtCore.QRect(230, 290, 101, 31))
        self.pushButton_fun1.setObjectName("pushButton_fun1")
        self.pushButton_load = QtWidgets.QPushButton(Formwin2)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_fun11 = QtWidgets.QPushButton(Formwin2)
        self.pushButton_fun11.setGeometry(QtCore.QRect(350, 290, 101, 31))
        self.pushButton_fun11.setObjectName("pushButton_fun11")
        self.label_jieguo = QtWidgets.QLabel(Formwin2)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")

        self.retranslateUi(Formwin2)
        QtCore.QMetaObject.connectSlotsByName(Formwin2)

    def retranslateUi(self, Formwin2):
        _translate = QtCore.QCoreApplication.translate
        Formwin2.setWindowTitle(_translate("Formwin2", "Form"))
        self.pushButton_fun0.setText(_translate("Formwin2", "水平翻转"))
        self.pushButton_save.setText(_translate("Formwin2", "保存图片"))
        self.label_tips.setText(_translate("Formwin2", "操作："))
        self.label_daichuli.setText(_translate("Formwin2", "待处理"))
        self.pushButton_fun1.setText(_translate("Formwin2", "垂直翻转"))
        self.pushButton_load.setText(_translate("Formwin2", "选择图片"))
        self.pushButton_fun11.setText(_translate("Formwin2", "沿xy轴翻转"))
        self.label_jieguo.setText(_translate("Formwin2", "结果"))


class Ui_Formwin3(object):
    def setupUi(self, Formwin3):
        Formwin3.setObjectName("Formwin3")
        Formwin3.resize(571, 400)
        self.pushButton_save = QtWidgets.QPushButton(Formwin3)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_zhifangtu = QtWidgets.QPushButton(Formwin3)
        self.pushButton_zhifangtu.setGeometry(QtCore.QRect(300, 290, 101, 31))
        self.pushButton_zhifangtu.setObjectName("pushButton_zhifangtu")
        self.label_daichuli = QtWidgets.QLabel(Formwin3)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin3)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_lap = QtWidgets.QPushButton(Formwin3)
        self.pushButton_lap.setGeometry(QtCore.QRect(160, 290, 101, 31))
        self.pushButton_lap.setObjectName("pushButton_lap")
        self.pushButton_gama = QtWidgets.QPushButton(Formwin3)
        self.pushButton_gama.setGeometry(QtCore.QRect(300, 340, 101, 31))
        self.pushButton_gama.setObjectName("pushButton_gama")
        self.pushButton_load = QtWidgets.QPushButton(Formwin3)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.label_tips = QtWidgets.QLabel(Formwin3)
        self.label_tips.setGeometry(QtCore.QRect(30, 280, 51, 41))
        self.label_tips.setObjectName("label_tips")
        self.label = QtWidgets.QLabel(Formwin3)
        self.label.setGeometry(QtCore.QRect(90, 350, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit_power_value = QtWidgets.QLineEdit(Formwin3)
        self.lineEdit_power_value.setGeometry(QtCore.QRect(160, 340, 101, 31))
        self.lineEdit_power_value.setObjectName("lineEdit_power_value")

        self.retranslateUi(Formwin3)
        QtCore.QMetaObject.connectSlotsByName(Formwin3)

    def retranslateUi(self, Formwin3):
        _translate = QtCore.QCoreApplication.translate
        Formwin3.setWindowTitle(_translate("Formwin3", "Form"))
        self.pushButton_save.setText(_translate("Formwin3", "保存图片"))
        self.pushButton_zhifangtu.setText(_translate("Formwin3", "直方图均衡"))
        self.label_daichuli.setText(_translate("Formwin3", "待处理"))
        self.label_jieguo.setText(_translate("Formwin3", "结果"))
        self.pushButton_lap.setText(_translate("Formwin3", "拉普拉斯变化"))
        self.pushButton_gama.setText(_translate("Formwin3", "伽马变化"))
        self.pushButton_load.setText(_translate("Formwin3", "选择图片"))
        self.label_tips.setText(_translate("Formwin3", "操作："))
        self.label.setText(_translate("Formwin3", "power1="))
        self.lineEdit_power_value.setText(_translate("Formwin3", "1.5"))


class Ui_Formwin4(object):
    def setupUi(self, Formwin4):
        Formwin4.setObjectName("Formwin4")
        Formwin4.resize(571, 400)
        self.label_daichuli = QtWidgets.QLabel(Formwin4)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.pushButton_junzhi = QtWidgets.QPushButton(Formwin4)
        self.pushButton_junzhi.setGeometry(QtCore.QRect(230, 330, 101, 31))
        self.pushButton_junzhi.setObjectName("pushButton_junzhi")
        self.pushButton_zhongzhi = QtWidgets.QPushButton(Formwin4)
        self.pushButton_zhongzhi.setGeometry(QtCore.QRect(230, 280, 101, 31))
        self.pushButton_zhongzhi.setObjectName("pushButton_zhongzhi")
        self.pushButton_save = QtWidgets.QPushButton(Formwin4)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_load = QtWidgets.QPushButton(Formwin4)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_fangbo = QtWidgets.QPushButton(Formwin4)
        self.pushButton_fangbo.setGeometry(QtCore.QRect(100, 280, 101, 31))
        self.pushButton_fangbo.setObjectName("pushButton_fangbo")
        self.pushButton_gauss = QtWidgets.QPushButton(Formwin4)
        self.pushButton_gauss.setGeometry(QtCore.QRect(100, 330, 101, 31))
        self.pushButton_gauss.setObjectName("pushButton_gauss")
        self.label_jieguo = QtWidgets.QLabel(Formwin4)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_suangbian = QtWidgets.QPushButton(Formwin4)
        self.pushButton_suangbian.setGeometry(QtCore.QRect(360, 280, 101, 31))
        self.pushButton_suangbian.setObjectName("pushButton_suangbian")

        self.retranslateUi(Formwin4)
        QtCore.QMetaObject.connectSlotsByName(Formwin4)

    def retranslateUi(self, Formwin4):
        _translate = QtCore.QCoreApplication.translate
        Formwin4.setWindowTitle(_translate("Formwin4", "Form"))
        self.label_daichuli.setText(_translate("Formwin4", "待处理"))
        self.pushButton_junzhi.setText(_translate("Formwin4", "均值滤波"))
        self.pushButton_zhongzhi.setText(_translate("Formwin4", "中值滤波"))
        self.pushButton_save.setText(_translate("Formwin4", "保存图片"))
        self.pushButton_load.setText(_translate("Formwin4", "选择图片"))
        self.pushButton_fangbo.setText(_translate("Formwin4", "方块滤波"))
        self.pushButton_gauss.setText(_translate("Formwin4", "高斯滤波"))
        self.label_jieguo.setText(_translate("Formwin4", "结果"))
        self.pushButton_suangbian.setText(_translate("Formwin4", "双边滤波"))


class Ui_Formwin5(object):
    def setupUi(self, Formwin5):
        Formwin5.setObjectName("Formwin5")
        Formwin5.resize(571, 400)
        self.pushButton_lunkuo = QtWidgets.QPushButton(Formwin5)
        self.pushButton_lunkuo.setGeometry(QtCore.QRect(310, 320, 101, 31))
        self.pushButton_lunkuo.setObjectName("pushButton_lunkuo")
        self.label_jieguo = QtWidgets.QLabel(Formwin5)
        self.label_jieguo.setGeometry(QtCore.QRect(300, 40, 201, 201))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin5)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 260, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.label_daichuli = QtWidgets.QLabel(Formwin5)
        self.label_daichuli.setGeometry(QtCore.QRect(70, 40, 201, 201))
        self.label_daichuli.setObjectName("label_daichuli")
        self.pushButton_save = QtWidgets.QPushButton(Formwin5)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 260, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_sobel = QtWidgets.QPushButton(Formwin5)
        self.pushButton_sobel.setGeometry(QtCore.QRect(140, 320, 101, 31))
        self.pushButton_sobel.setObjectName("pushButton_sobel")

        self.retranslateUi(Formwin5)
        QtCore.QMetaObject.connectSlotsByName(Formwin5)

    def retranslateUi(self, Formwin5):
        _translate = QtCore.QCoreApplication.translate
        Formwin5.setWindowTitle(_translate("Formwin5", "Form"))
        self.pushButton_lunkuo.setText(_translate("Formwin5", "轮廓检测"))
        self.label_jieguo.setText(_translate("Formwin5", "结果"))
        self.pushButton_load.setText(_translate("Formwin5", "选择图片"))
        self.label_daichuli.setText(_translate("Formwin5", "待处理"))
        self.pushButton_save.setText(_translate("Formwin5", "保存图片"))
        self.pushButton_sobel.setText(_translate("Formwin5", "sobel检测"))


class Ui_Formwin6(object):
    def setupUi(self, Formwin6):
        Formwin6.setObjectName("Formwin6")
        Formwin6.resize(571, 400)
        self.label_jieguo = QtWidgets.QLabel(Formwin6)
        self.label_jieguo.setGeometry(QtCore.QRect(300, 40, 201, 201))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_save = QtWidgets.QPushButton(Formwin6)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 260, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_load = QtWidgets.QPushButton(Formwin6)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 260, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.label_daichuli = QtWidgets.QLabel(Formwin6)
        self.label_daichuli.setGeometry(QtCore.QRect(70, 40, 201, 201))
        self.label_daichuli.setObjectName("label_daichuli")
        self.pushButton_halisi = QtWidgets.QPushButton(Formwin6)
        self.pushButton_halisi.setGeometry(QtCore.QRect(90, 320, 131, 31))
        self.pushButton_halisi.setObjectName("pushButton_halisi")
        self.pushButton_ORB = QtWidgets.QPushButton(Formwin6)
        self.pushButton_ORB.setGeometry(QtCore.QRect(350, 320, 101, 31))
        self.pushButton_ORB.setObjectName("pushButton_ORB")

        self.retranslateUi(Formwin6)
        QtCore.QMetaObject.connectSlotsByName(Formwin6)

    def retranslateUi(self, Formwin6):
        _translate = QtCore.QCoreApplication.translate
        Formwin6.setWindowTitle(_translate("Formwin6", "Form"))
        self.label_jieguo.setText(_translate("Formwin6", "结果"))
        self.pushButton_save.setText(_translate("Formwin6", "保存图片"))
        self.pushButton_load.setText(_translate("Formwin6", "选择图片"))
        self.label_daichuli.setText(_translate("Formwin6", "待处理"))
        self.pushButton_halisi.setText(_translate("Formwin6", "哈里斯角检测"))
        self.pushButton_ORB.setText(_translate("Formwin6", "ORB特征检测"))