# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Formwin4(object):
    def setupUi(self, Formwin4):
        Formwin4.setObjectName("Formwin4")
        Formwin4.resize(571, 400)
        self.label_daichuli = QtWidgets.QLabel(Formwin4)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.pushButton_junzhi = QtWidgets.QPushButton(Formwin4)
        self.pushButton_junzhi.setGeometry(QtCore.QRect(230, 330, 101, 31))
        self.pushButton_junzhi.setObjectName("pushButton_junzhi")
        self.pushButton_zhongzhi = QtWidgets.QPushButton(Formwin4)
        self.pushButton_zhongzhi.setGeometry(QtCore.QRect(230, 280, 101, 31))
        self.pushButton_zhongzhi.setObjectName("pushButton_zhongzhi")
        self.pushButton_save = QtWidgets.QPushButton(Formwin4)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_load = QtWidgets.QPushButton(Formwin4)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_fangbo = QtWidgets.QPushButton(Formwin4)
        self.pushButton_fangbo.setGeometry(QtCore.QRect(100, 280, 101, 31))
        self.pushButton_fangbo.setObjectName("pushButton_fangbo")
        self.pushButton_gauss = QtWidgets.QPushButton(Formwin4)
        self.pushButton_gauss.setGeometry(QtCore.QRect(100, 330, 101, 31))
        self.pushButton_gauss.setObjectName("pushButton_gauss")
        self.label_jieguo = QtWidgets.QLabel(Formwin4)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_suangbian = QtWidgets.QPushButton(Formwin4)
        self.pushButton_suangbian.setGeometry(QtCore.QRect(360, 280, 101, 31))
        self.pushButton_suangbian.setObjectName("pushButton_suangbian")

        self.retranslateUi(Formwin4)
        QtCore.QMetaObject.connectSlotsByName(Formwin4)

    def retranslateUi(self, Formwin4):
        _translate = QtCore.QCoreApplication.translate
        Formwin4.setWindowTitle(_translate("Formwin4", "Form"))
        self.label_daichuli.setText(_translate("Formwin4", "待处理"))
        self.pushButton_junzhi.setText(_translate("Formwin4", "均值滤波"))
        self.pushButton_zhongzhi.setText(_translate("Formwin4", "中值滤波"))
        self.pushButton_save.setText(_translate("Formwin4", "保存图片"))
        self.pushButton_load.setText(_translate("Formwin4", "选择图片"))
        self.pushButton_fangbo.setText(_translate("Formwin4", "方波滤波"))
        self.pushButton_gauss.setText(_translate("Formwin4", "高斯滤波"))
        self.label_jieguo.setText(_translate("Formwin4", "结果"))
        self.pushButton_suangbian.setText(_translate("Formwin4", "双边滤波"))
